{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: init-db-job
spec:
  template:
    spec:
      containers:
        - name: init-db
          image: postgres:latest
          env:
            - name: PGPASSWORD
              value: "password"
          command: ["psql"]
          args:
            - "-h"
            - "postgres"
            - "-U"
            - "user"
            - "-f"
            - "/scripts/init-db.sql"
          volumeMounts:
            - name: init-db-script-volume
              mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
        - name: init-db-script-volume
          configMap:
            name: init-db-script
            items:
              - key: init-db.sql
                path: init-db.sql
{{- end }}