apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgresql.image }}:{{ .Values.postgresql.tag }}"
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgresql.db }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgresql.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresql.password }}"
          ports:
            - containerPort: { { .Values.postgresql.port } }
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
