apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  ports:
    - port: { { .Values.postgresql.port } }
      targetPort: { { .Values.postgresql.port } }
      protocol: TCP
  selector:
    app: postgres
